[arduino]
srcdir = "$HOME/.local/Arduino"
links = [
    ["{{vim}}/bundle/vim-blueper/themes/arduino/blueper.zip", "theme/blueper.zip"]
]

[bat]
srcdir = "$HOME/.config/bat"
links = [
    ["config"],
    ["{{vim}}/bundle/vim-blueper/themes/tmTheme/Blueper.tmTheme", "themes/Blueper.tmTheme"],
]

[ctags]
srcdir = "$HOME/.config/ctags"
links = [
    [".ctags", "config.ctags"],
]

[fish]
srcdir = "$HOME/.config/fish"
links = [
    [".", "$HOME/.config/fish"],
    ["{{vim}}/bundle/vim-blueper/themes/fish/blueper_colors.fish", "conf.d/blueper_colors.fish"],
    ["{{vim}}/bundle/vim-blueper/themes/fish/blueper.fish", "conf.d/blueper.fish"],
]

[fonts]
srcdir = "$HOME/.config/fontconfig"
links = [
    ["fonts.conf"],
]

[git]
description = "Git config"
links = [
    [".gitconfig"],
    ["ignore", ".config/git/ignore"],
]

[grip]
links = [
    [".", ".config/grip"],
]

[kitty]
srcdir = "$HOME/.config/kitty"
links = [
    ["kitty.conf"],
    ["{{vim}}/bundle/vim-blueper/themes/kitty/colors.conf", "colors.conf"],
]

[misc]
links = [
    [".ghci"],
    [".vintrc.yaml"],
    [".screenrc"],
    [".fdignore"],
    [".jackdrc"],
    [".bibcleanrc", "$HOME/.config/bibclean/config"],
    [".chktexrc", ".config/chktex/.chktexrc"],
]

[python]
links = [
    ["flake8", ".config/flake8"],
    ["pylintrc", ".config/pylintrc"],
]

[qutebrowser]
srcdir = "$HOME/.config/qutebrowser"
links = [
    ["config.py"],
    ["{{vim}}/bundle/vim-blueper/themes/qutebrowser/blueper.py", "blueper.py"],
    ["qutebrowser", "$HOME/.local/bin/qutebrowser"],
]

[vim]
links = [
    [".", ".vim"],
    [".vimrc"],
]

[neovim]
dstdir = "vim"
srcdir = "$HOME/.config/nvim"
links = [
    ["autoload"],
    ["bundle"],
    ["colors"],
    [".vimrc", "init.vim"],
]

[scripts]
srcdir = "$HOME/.local/bin"
links = [
    ["bin", "setuid_scripts"],
]

[ssh]
srcdir = "$HOME/.ssh"
links = [
    ["config"],
]

[xmonad]
links = [
    [".", ".xmonad"],
    [".xmobarrc"],
]
