[bat]
srcdir = "$HOME/.config/bat"
links = [
    ["config"],
    ["{{vim}}/bundle/vim-blueper/themes/tmTheme/Blueper.tmTheme", "themes/Blueper.tmTheme"],
]

[ctags]
srcdir = "$HOME/.config/ctags"
links = [
    [".ctags", "config.ctags"],
]

[fish]
links = [
    [".", ".config/fish"],
]

[git]
description = "Git config"
links = [
    [".gitconfig"],
    ["ignore", ".config/git/ignore"],
]

[grip]
links = [
    [".", ".config/grip"],
]

[kitty]
srcdir = "$HOME/.config/kitty"
links = [
    ["kitty.conf"],
    ["{{vim}}/bundle/vim-blueper/themes/kitty/colors.conf", "colors.conf"],
]

[misc]
links = [
    [".ghci"],
    [".vintrc.yaml"],
    [".screenrc"],
    [".fdignore"],
    [".jackdrc"],
]

[qutebrowser]
srcdir = "$HOME/.config/qutebrowser"
links = [
    ["config.py"],
    ["{{vim}}/bundle/vim-blueper/themes/qutebrowser/blueper.py", "blueper.py"],
    ["qutebrowser", "$HOME/bin/qutebrowser"],
]

[vim]
links = [
    [".", ".vim"],
    [".vimrc"],
]

[neovim]
dstdir = "vim"
srcdir = "$HOME/.config/nvim"
links = [
    ["autoload"],
    ["bundle"],
    ["colors"],
    [".vimrc", "init.vim"],
]

[ssh]
srcdir = "$HOME/.ssh"
links = [
    ["config"],
]

[xmonad]
links = [
    [".", ".xmonad"],
    [".xmobarrc"],
]
